---
kind: Secret
apiVersion: v1
metadata:
  name: aws-credentials
  labels:
    app: scale-test
stringData:
  AWS_ACCESS_KEY_ID: {{ .KUADRANT_AWS_ACCESS_KEY_ID }}
  AWS_REGION: {{ .KUADRANT_AWS_REGION }}
  AWS_SECRET_ACCESS_KEY: {{ .KUADRANT_AWS_SECRET_ACCESS_KEY }}
type: kuadrant.io/aws
