{{- $GW_NUM := .GW_NUM }}
apiVersion: kuadrant.io/v1
kind: DNSPolicy
metadata:
  name: dns-policy-gw{{$GW_NUM}}-i{{ .Iteration }}
  labels: 
    app: scale-test
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: gw{{$GW_NUM}}-i{{ .Iteration }}
  providerRefs:
  - name: aws-credentials
