{{- $GW_NUM := .GW_NUM }}
apiVersion: kuadrant.io/v1
kind: RateLimitPolicy
metadata:
  name: rlp-gw{{$GW_NUM}}-i{{ .Iteration }}
  labels: 
    app: scale-test
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: gw{{$GW_NUM}}-i{{ .Iteration }}
  limits:
    "global":
      rates:
      - limit: 3
        window: "10s"
