{{- $Iteration := .Iteration }}
{{- $KUADRANT_ZONE_ROOT_DOMAIN := .KUADRANT_ZONE_ROOT_DOMAIN }}
{{- $GW_NUM := .GW_NUM }}
{{- $LISTENER_NUM := .LISTENER_NUM }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata: 
  name: httproute-gw{{$GW_NUM}}-l{{$LISTENER_NUM}}-i{{ .Iteration }}
  labels: 
    app: scale-test
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: gw{{$GW_NUM}}-i{{ .Iteration }}
    sectionName: api-{{$LISTENER_NUM}}
  hostnames:
  - "api.scale-test-gw{{$GW_NUM}}-l{{$LISTENER_NUM}}-i{{$Iteration}}.{{$KUADRANT_ZONE_ROOT_DOMAIN}}"
  rules:
  - backendRefs:
    - group: ''
      kind: Service
      name: httpbin
      port: 8080
      weight: 1
    matches:
      - path:
          type: PathPrefix
          value: /
