{{- $GW_NUM := .GW_NUM }}
{{- $LISTENER_NUM := .LISTENER_NUM }}
apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: httproute-auth-policy-gw{{$GW_NUM}}-l{{$LISTENER_NUM}}-i{{ .Iteration }}
  labels: 
    app: scale-test
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: httproute-gw{{$GW_NUM}}-l{{$LISTENER_NUM}}-i{{ .Iteration }}
  rules:
    authorization:
      allow-all:
        opa:
          rego: "allow = true"
    authentication:
      "api-key-users":
        apiKey:
          allNamespaces: true
          selector:
            matchLabels:
              app: scale-test
        credentials:
          authorizationHeader:
            prefix: APIKEY
    response:
      success:
        filters:
          "identity":
            json:
              properties:
                "userid":
                  selector: auth.identity.metadata.annotations.secret\.kuadrant\.io/user-id
