apiVersion: v1
kind: Secret
metadata:
  name: {{.person}}-key
  labels:
    authorino.kuadrant.io/managed-by: authorino
    app: scale-test
  annotations:
    secret.kuadrant.io/user-id: {{.person}}
stringData:
  api_key: iam{{.person}}
type: Opaque
