{{- $KUADRANT_ZONE_ROOT_DOMAIN := .KUADRANT_ZONE_ROOT_DOMAIN }}
{{- $NUM_LISTENERS := .NUM_LISTENERS }}
---
metricsEndpoints: 
  - endpoint: {{ .PROMETHEUS_URL }}
    token: {{ .PROMETHEUS_TOKEN }}
    metrics: 
    - ./metrics.yaml
{{ if .OS_INDEXING }}
    indexer:
      type: opensearch
      esServers: ["{{ .ES_SERVER }}"]
      insecureSkipVerify: true
      defaultIndex: kube-burner
{{ else }}
    indexer:
      type: local
      metricsDirectory: ./metrics
{{ end }}
global:
{{ if .SKIP_CLEANUP }}
  gc: false
{{ else }}
  gc: true
{{ end }}
jobs: 
  - name: scale-test-preparations
    jobIterations: 1
    qps: 1
    burst: 1
    namespacedIterations: true
    namespace: scale-test
    waitWhenFinished: true
    objects:
      - objectTemplate: templates/httpbin-deployment.yaml
        kind: Deployment
        replicas: 1
        waitOptions:
          customStatusPaths:
            - key: '(.conditions.[] | select(.type == "Available")).status'
              value: "True"
      - objectTemplate: templates/httpbin-service.yaml
        kind: Service
        replicas: 1
      - objectTemplate: templates/aws-credentials.yaml
        kind: Secret
        replicas: 1
        inputVars:
          KUADRANT_AWS_ACCESS_KEY_ID: "{{ .KUADRANT_AWS_ACCESS_KEY_ID }}"
          KUADRANT_AWS_REGION: "{{ .KUADRANT_AWS_REGION }}"
          KUADRANT_AWS_SECRET_ACCESS_KEY: "{{ .KUADRANT_AWS_SECRET_ACCESS_KEY }}"
      - objectTemplate: templates/person-secret.yaml
        kind: Secret
        replicas: 1
        inputVars:
          person: "alice"
      - objectTemplate: templates/person-secret.yaml
        kind: Secret
        replicas: 1
        inputVars:
          person: "bob"
  - name: scale-test-main
    jobIterations: 1
    qps: 1
    burst: 1
    jobPause: 3m
    namespacedIterations: true
    namespace: scale-test
    waitWhenFinished: true
    objects:
{{- $numGWs := .NUM_GWS | atoi }}
{{- range $index := until $numGWs }}
  {{- $GW_NUM := add1 $index }}
      - objectTemplate: templates/gw-tls.yaml
        replicas: 1
        waitOptions:
          customStatusPaths:
            - key: '(.conditions.[] | select(.type == "Programmed")).status'
              value: "True"
        inputVars:
          KUADRANT_ZONE_ROOT_DOMAIN: "{{$KUADRANT_ZONE_ROOT_DOMAIN}}"
          NUM_LISTENERS: "{{$NUM_LISTENERS}}"
          GW_NUM: "{{$GW_NUM}}"
      - objectTemplate: templates/gw-tls-policy.yaml
        replicas: 1
        waitOptions:
          customStatusPaths:
            - key: '(.conditions.[] | select(.type == "Enforced")).status'
              value: "True"
        inputVars:
          GW_NUM: "{{$GW_NUM}}"
      - objectTemplate: templates/gw-dns-policy.yaml
        replicas: 1
        waitOptions:
          customStatusPaths:
            - key: '(.conditions.[] | select(.type == "Enforced")).status'
              value: "True"
        inputVars:
          GW_NUM: "{{$GW_NUM}}"
      - objectTemplate: templates/gw-rlp.yaml
        replicas: 1
        waitOptions:
          customStatusPaths:
            - key: '(.conditions.[] | select(.type == "Accepted")).status'
              value: "True"
        inputVars:
          GW_NUM: "{{$GW_NUM}}"
      - objectTemplate: templates/gw-auth-policy.yaml
        replicas: 1
        waitOptions:
          customStatusPaths:
            - key: '(.conditions.[] | select(.type == "Accepted")).status'
              value: "True"
        inputVars:
          GW_NUM: "{{$GW_NUM}}"
  {{- range $index := until ($NUM_LISTENERS | atoi)}}
    {{- $LISTENER_NUM := add1 $index }}
      - objectTemplate: templates/httproute-listener.yaml
        replicas: 1
        waitOptions:
          customStatusPaths:
            - key: '(.parents[] | select(.controllerName == "istio.io/gateway-controller")).conditions[] | select(.type == "Accepted").status'
              value: "True"
        inputVars:
          KUADRANT_ZONE_ROOT_DOMAIN: "{{$KUADRANT_ZONE_ROOT_DOMAIN}}"
          GW_NUM: "{{$GW_NUM}}"
          LISTENER_NUM: "{{$LISTENER_NUM}}"
      - objectTemplate: templates/httproute-rlp.yaml
        replicas: 1
        waitOptions:
          customStatusPaths:
            - key: '(.conditions.[] | select(.type == "Accepted")).status'
              value: "True"
        inputVars:
          GW_NUM: "{{$GW_NUM}}"
          LISTENER_NUM: "{{$LISTENER_NUM}}"
      - objectTemplate: templates/httproute-auth-policy.yaml
        replicas: 1
        waitOptions:
          customStatusPaths:
            - key: '(.conditions.[] | select(.type == "Accepted")).status'
              value: "True"
        inputVars:
          GW_NUM: "{{$GW_NUM}}"
          LISTENER_NUM: "{{$LISTENER_NUM}}"
  {{- end }}
{{- end }}
{{- if not .SKIP_CLEANUP }}
  - name: scale-test-safe-dnspolicy-cleanup
    jobType: delete
    jobIterations: 1
    namespacedIterations: true
    namespace: scale-test
    jobPause: 2m # to allow DNSRecords to be removed
    waitWhenFinished: true
    objects:
      - kind: DNSPolicy
        apiVersion: kuadrant.io/v1alpha1
        labelSelector: {kube-burner-job: scale-test-main}
{{- end }}
